Shipment.WebUI/Models/ErrorViewModel.cs
using System;

namespace Shipment.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Shipment.WebUI/Controllers/ShipmentController.cs
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Shipment.ObjectModel.DTO;
using Shipment.ObjectModel.Response;
using Shipment.WebUI.Models;

namespace Shipment.WebUI.Controllers
{
    public class ShipmentController : Controller
    {
        private readonly ApiClient.IApiClient _apiClient;

        public ShipmentController(ApiClient.IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public IActionResult Index()
        {
            GetShipmentPackagesResponse response = _apiClient.GetShipmentPackages();
            
            if (response != null && response.ShipmentPackages != null)
            {
                return View(response.ShipmentPackages);
            }
            
            return View(new List<ShipmentPackageDTO>());
        }

        public IActionResult QueryShipment(string packageNumber)
        {
            if (string.IsNullOrEmpty(packageNumber))
            {
                return View();
            }

            QuerySpecificPackageResponse response = _apiClient.QuerySpecificPackage(packageNumber);

            if (response != null && response.ShipmentPackage != null)
            {
                return View(response.ShipmentPackage);
            }
            else
            {
                ViewBag.Message = $"Could not find a package with the following number: {packageNumber}";
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Shipment.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shipment Tracking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Shipment" asp-action="Index">Shipment Tracking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shipment" asp-action="Index">Shipments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shipment" asp-action="QueryShipment">Query Shipment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OGOO Digital
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Shipment.WebUI/Views/Shipment/Index.cshtml
@model IEnumerable<Shipment.ObjectModel.DTO.ShipmentPackageDTO>

@{
    ViewData["Title"] = "Shipments List";
}

<div class="text-center">
    <h1>Today's Shipments</h1>
    <p>Red lines mean return to delivery center.</p>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PackageNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeliveryAddressNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PackageWeightInKilos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApproximateDeliveryTime)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td @{if (item.LastStopOfTour) { <text>style="border-bottom: 1pt solid crimson;"</text> }}>
                    @Html.DisplayFor(modelItem => item.PackageNumber)
                </td>
                <td @{if (item.LastStopOfTour) { <text>style="border-bottom: 1pt solid crimson;"</text> }}>
                    @Html.DisplayFor(modelItem => item.DeliveryAddressNumber)
                </td>
                <td @{if (item.LastStopOfTour) { <text>style="border-bottom: 1pt solid crimson;"</text> }}>
                    @Html.DisplayFor(modelItem => item.PackageWeightInKilos) kg
                </td>
                <td @{if (item.LastStopOfTour) { <text>style="border-bottom: 1pt solid crimson;"</text> }}>
                    @Html.DisplayFor(modelItem => item.ApproximateDeliveryTime)
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Shipment.WebUI/Views/Shipment/QueryShipment.cshtml
@model Shipment.ObjectModel.DTO.ShipmentPackageDTO

@{
    ViewData["Title"] = "Query Shipment";
}

<div class="text-center">
    <h1>Query Shipment</h1>

    <p>You can query your shipment details using the Package Number</p>

    <div>
        @using (Html.BeginForm())
        {
            <p>
                Package Number: @Html.TextBox("PackageNumber")
                <input type="submit" value="Search" />
            </p>
        }
    </div>
</div>

<br />

@if (Model != null)
{
    <div>
        <h4>Package Details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PackageNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PackageNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DeliveryAddressNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DeliveryAddressNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PackageWeightInKilos)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PackageWeightInKilos) kg
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ApproximateDeliveryTime)
            </dt>
            <dd class="col-sm-10">
                @if (Model.ApproximateDeliveryTime.HasValue)
                {
                    @Html.DisplayFor(model => model.ApproximateDeliveryTime)
                }
                else
                {
                    @Html.Label("WontBeDelivered", "Package will not be delivered today.")
                }
            </dd>
        </dl>
    </div>
}
else
{

    <div class="text-center">
        <p>@ViewBag.Message</p>
    </div>
}